'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useClinic } from './clinic-provider';
import { digits, formatDate, normalizePhone, speciesLabels, type Patient } from '@/lib/clinic';

export function ClinicDashboard({today,patientsOnly=false}:{today:string;patientsOnly?:boolean}) {
 const {patients,records,addPatient,busy}=useClinic();
 const [query,setQuery]=useState(''),[adding,setAdding]=useState(false),[error,setError]=useState('');
 const filtered=patients.filter(p=>digits(`${p.name} ${p.owner} ${p.phone}`).includes(digits(query.trim())));
 const vaccines=records.filter(r=>r.kind==='vaccine'&&r.nextDate);
 const reminders=records.filter(r=>r.kind==='reminder'&&!r.completed);
 async function register(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get('name')||'').trim(),owner=String(data.get('owner')||'').trim(),phone=normalizePhone(String(data.get('phone')||'')),species=String(data.get('species')) as Patient['species'];if(!name||name.length>80||!owner||owner.length>120||!phone||!(species in speciesLabels)){setError('نام حیوان، نام صاحب و شماره موبایل معتبر را وارد کنید.');return;}if(!await addPatient({id:crypto.randomUUID(),name,owner,phone,species}))return;setAdding(false);setError('');}
 return <><div className="page-heading"><div><p className="eyebrow">{formatDate(today)}</p><h1>{patientsOnly?'بیماران':'سلام دکتر'}</h1><p className="muted">{patientsOnly?'پرونده هر بیمار، همیشه در دسترس.':'امروز هم، کنار شما برای مراقبت بهتر.'}</p></div><button className="primary" onClick={()=>setAdding(!adding)}>{adding?'بستن فرم':'+ ثبت بیمار'}</button></div>
 {!patientsOnly&&<section className="stats" aria-label="خلاصه امروز">{[['بیماران ثبت‌شده',patients.length,'♡'],['واکسن‌های امروز',vaccines.filter(r=>r.nextDate===today).length,'✚'],['یادآوری‌های امروز',reminders.filter(r=>r.date===today).length,'◇'],['واکسن‌های عقب‌افتاده',vaccines.filter(r=>r.nextDate<today).length,'◷']].map(([label,value,icon],i)=><div className={`stat stat-${i}`} key={label}><span className="stat-icon" aria-hidden="true">{icon}</span><p>{label}</p><strong>{Number(value).toLocaleString('fa-IR')}</strong><small>{i===3?'نیازمند پیگیری':'در پرونده‌های کلینیک'}</small></div>)}</section>}
 {adding&&<section className="panel registration"><h2>ثبت بیمار جدید</h2><p className="muted">چهار مشخصه برای شروع یک پرونده.</p><form onSubmit={register} noValidate><div className="form-grid"><label>نام حیوان *<input name="name" autoFocus maxLength={80} autoComplete="off"/></label><label>نوع حیوان *<select name="species">{Object.entries(speciesLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>نام و نام خانوادگی صاحب *<input name="owner" maxLength={120} autoComplete="name"/></label><label>شماره موبایل *<input name="phone" type="tel" dir="ltr" maxLength={20} placeholder="۰۹۱۲…" autoComplete="tel"/></label></div>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button disabled={busy} className="primary">{busy?'در حال ذخیره…':'ثبت بیمار'}</button><button type="button" onClick={()=>setAdding(false)}>انصراف</button></div></form></section>}
 <div className={patientsOnly?'':'dashboard-columns'}><section className="panel"><div className="section-heading"><h2>{patientsOnly?'فهرست بیماران':'پرونده‌های بیماران'}</h2><span className="pill">{patients.length.toLocaleString('fa-IR')} بیمار</span></div><label className="search"><span className="sr-only">جست‌وجوی بیمار</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام بیمار، صاحب یا شماره موبایل…"/></label><div className="patient-list">{filtered.length?filtered.map(p=>{const last=records.filter(r=>r.petId===p.id&&r.kind==='visit').sort((a,b)=>b.date.localeCompare(a.date))[0];return <Link className="patient-row" key={p.id} href={`/patients/${p.id}`}><span className="avatar" aria-hidden="true">{p.name.slice(0,1)}</span><div><h3>{p.name}<span className="species">{speciesLabels[p.species]}</span></h3><p>{p.owner} · <bdi>{p.phone}</bdi></p><small>آخرین ویزیت: {last?`${last.title} · ${formatDate(last.date)}`:'هنوز ثبت نشده'}</small></div><span className="row-arrow" aria-hidden="true">←</span></Link>}):<div className="empty"><span aria-hidden="true">♡</span><h3>{query?'بیماری پیدا نشد':'اولین پرونده را بسازید'}</h3><p>{query?'نام یا شماره دیگری را جست‌وجو کنید.':'با ثبت بیمار، سوابق و پیگیری‌های او را اینجا ببینید.'}</p>{!query&&<button onClick={()=>setAdding(true)}>+ ثبت اولین بیمار</button>}</div>}</div></section>
 {!patientsOnly&&<section className="panel"><div className="section-heading"><h2>در انتظار پیگیری</h2><Link href="/reminders">همه یادآوری‌ها ←</Link></div><p className="muted">واکسن‌ها و اقدام‌های برنامه‌ریزی‌شده</p>{[...vaccines.map(r=>({...r,due:r.nextDate})),...reminders.map(r=>({...r,due:r.date}))].sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5).map(r=><Link className="due-row" href={`/patients/${r.petId}`} key={r.id}><span className={`pill ${r.due<today?'warning':''}`}>{r.due<today?'عقب‌افتاده':'پیش رو'}</span><h3>{r.title} · {patients.find(p=>p.id===r.petId)?.name}</h3><p>{formatDate(r.due)}</p></Link>)}{!vaccines.length&&!reminders.length&&<div className="empty"><span aria-hidden="true">◇</span><h3>پیگیری ثبت نشده است</h3><p>از پرونده بیمار، موعد واکسن یا یادآوری یک اقدام را ثبت کنید.</p></div>}</section>}</div></>;
}
