'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useClinic } from './clinic-provider';
import { JalaliField } from './jalali-field';
import { todayISO, formatDate, speciesLabels, visitLabels, type RecordEntry } from '@/lib/clinic';

export function PatientProfile({id,today}:{id:string;today:string}) {
 const {patients,records,addRecord,completeReminder,busy}=useClinic();
 const pet=patients.find(p=>p.id===id);
 const [kind,setKind]=useState<RecordEntry['kind']|null>(null),[date,setDate]=useState(today),[nextDate,setNextDate]=useState(today),[error,setError]=useState('');
 const history=records.filter(r=>r.petId===id).sort((a,b)=>b.date.localeCompare(a.date));
 const last=history.find(r=>r.kind==='visit');
 if(!pet)return <section className="panel empty"><h1>پرونده در دسترس نیست</h1><p>بیمار موردنظر پیدا نشد. از فهرست بیماران پرونده را انتخاب کنید.</p><Link className="primary" href="/patients">بازگشت به بیماران</Link></section>;
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!kind)return;const submittedDate=kind==='visit'?todayISO():date;const data=new FormData(event.currentTarget);const title=String(data.get('title')||'').trim();const notes=String(data.get('notes')||'').trim();if(!title||title.length>120||notes.length>2000){setError('عنوان را وارد کنید؛ توضیحات باید حداکثر ۲۰۰۰ نویسه باشد.');return;}if((kind==='vaccine'||kind==='visit')&&date>today){setError('تاریخ انجام نمی‌تواند در آینده باشد.');return;}if(kind==='vaccine'&&nextDate<=date){setError('موعد بعدی باید پس از تاریخ تزریق باشد.');return;}if(kind==='reminder'&&date<today){setError('تاریخ یادآوری باید امروز یا پس از آن باشد.');return;}const saved=await addRecord({id:crypto.randomUUID(),petId:id,kind,title,date:submittedDate,nextDate:kind==='vaccine'?nextDate:'',notes,diagnosis:String(data.get('diagnosis')||'').slice(0,2000),treatment:String(data.get('treatment')||'').slice(0,2000),medications:String(data.get('medications')||'').slice(0,2000),completed:false});if(!saved)return;setKind(null);setError('');}
 function open(value:RecordEntry['kind']){setKind(value);setDate(today);setNextDate(today);setError('');}
 return <><Link className="back" href="/patients">→ بیماران</Link><section className="panel profile-header"><div className="avatar large">{pet.name.slice(0,1)}</div><div><p className="eyebrow">پرونده بیمار</p><h1>{pet.name}</h1><p className="muted">{speciesLabels[pet.species]} · صاحب: {pet.owner}</p><a href={`tel:${pet.phone}`}><bdi>{pet.phone}</bdi></a></div><div className="last-visit"><span className="muted">آخرین ویزیت</span><h3>{last?.title||'هنوز ثبت نشده'}</h3><p>{last?formatDate(last.date):'پس از ثبت مراجعه نمایش داده می‌شود'}</p></div></section><div className="profile-actions"><button className="primary" onClick={()=>open('visit')}>+ ثبت مراجعه</button><button onClick={()=>open('vaccine')}>+ ثبت واکسن</button><button onClick={()=>open('reminder')}>+ یادآوری اقدام</button></div>
 {kind&&<section className="panel registration"><h2>{kind==='visit'?'ثبت مراجعه':kind==='vaccine'?'ثبت واکسن':'یادآوری اقدام خاص'}</h2><form onSubmit={save} noValidate><div className="form-grid"><label>{kind==='visit'?'نوع ویزیت':kind==='vaccine'?'نام واکسن':'عنوان اقدام'} *{kind==='visit'?<select name="title">{Object.entries(visitLabels).map(([value,label])=><option key={value}>{label}</option>)}</select>:<input name="title" maxLength={120} placeholder={kind==='vaccine'?'مثلاً واکسن هاری':'مثلاً کشیدن بخیه یا تکرار آزمایش'}/>}</label>{kind==='visit'?<div className="visit-date"><span>تاریخ مراجعه</span><p><span className="pill">امروز</span> <time dateTime={today}>{formatDate(today)}</time></p><small>هنگام ثبت، تاریخ امروز به‌صورت خودکار درج می‌شود.</small></div>:<JalaliField label={kind==='reminder'?'زمان یادآوری':'تاریخ تزریق'} value={date} onChange={setDate} min={kind==='reminder'?today:undefined} max={kind==='vaccine'?today:undefined}/>}{kind==='vaccine'&&<JalaliField label="موعد واکسن بعدی" value={nextDate} onChange={setNextDate} min={date}/>}</div>{kind==='visit'&&<div className="form-grid">{[['diagnosis','تشخیص'],['treatment','درمان'],['medications','داروها']].map(([name,label])=><label className={name==='medications'?'full-field':undefined} key={name}>{label}<textarea name={name} maxLength={2000} rows={2}/></label>)}</div>}<label>{kind==='visit'?'علت مراجعه و توضیحات':'توضیحات'}<textarea name="notes" maxLength={2000} rows={3}/></label>{kind!=='visit'&&<p className="muted">ارسال پیامک طبق تنظیمات یادآوری کلینیک انجام می‌شود.</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button disabled={busy} className="primary">{busy?'در حال ذخیره…':'ثبت در پرونده'}</button><button type="button" onClick={()=>setKind(null)}>انصراف</button></div></form></section>}
 <div className="dashboard-columns"><section className="panel"><h2>سوابق بیمار</h2><p className="muted">مراجعه‌ها، واکسن‌ها و یادآوری‌ها به ترتیب تاریخ</p>{history.length?history.map(r=><article className="timeline-entry" key={r.id}><div className="section-heading"><span className="pill">{r.kind==='visit'?'مراجعه':r.kind==='vaccine'?'واکسن':'یادآوری'}</span><time dateTime={r.date}>{formatDate(r.date)}</time></div><h3>{r.title}</h3>{r.notes&&<p className="record-text">{r.notes}</p>}{[['تشخیص',r.diagnosis],['درمان',r.treatment],['داروها',r.medications]].map(([label,text])=>text&&<p className="record-text" key={label}><strong>{label}: </strong>{text}</p>)}{r.nextDate&&<p className="accent">موعد بعدی: {formatDate(r.nextDate)}</p>}{r.kind==='reminder'&&(r.completed?<span className="pill">انجام شد</span>:<button onClick={()=>completeReminder(r.id)}>علامت‌گذاری به‌عنوان انجام‌شده</button>)}</article>):<div className="empty"><span aria-hidden="true">✚</span><h3>داستان مراقبت از اینجا شروع می‌شود</h3><p>اولین مراجعه یا واکسن را به پرونده اضافه کنید.</p></div>}</section><aside className="panel"><h2>برنامه مراقبت</h2>{history.filter(r=>(r.kind==='vaccine'&&r.nextDate)||(r.kind==='reminder'&&!r.completed)).sort((a,b)=>(a.nextDate||a.date).localeCompare(b.nextDate||b.date)).map(r=><div className="due-row" key={r.id}><span className={`pill ${(r.nextDate||r.date)<today?'warning':''}`}>{(r.nextDate||r.date)<today?'عقب‌افتاده':'پیش رو'}</span><h3>{r.title}</h3><p>{formatDate(r.nextDate||r.date)}</p></div>)}{!history.some(r=>r.kind==='vaccine'||(r.kind==='reminder'&&!r.completed))&&<p className="empty">هنوز موعدی تعیین نشده است.</p>}</aside></div></>;
}
